name: Test, Build and Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        run: pytest --maxfail=1 --disable-warnings -q

  build:
    needs: test
    runs-on: windows-latest
    steps:
      - name: Prepare env file
        run: copy .env.example .env

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install nuitka

      - name: Build client exe
        run: |
          python -m nuitka --standalone --onefile --windows-disable-console --disable-dll-dependency-cache --assume-yes-for-downloads cli/client.py

      - name: Find built exe
        id: find_exe
        run: |
          $exe = Get-ChildItem -Path . -Filter "*.exe" | Select-Object -First 1
          echo "exe_path=$($exe.FullName)" >> $env:GITHUB_OUTPUT

      - name: Upload Release to GitHub
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.find_exe.outputs.exe_path }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
