name: Build and Release Client

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"
  pull_request:


jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install nuitka

      - name: Build exe with Nuitka
        run: |
          python -m nuitka --onefile --standalone --assume-yes-for-downloads client.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: client-exe
          path: ./*.exe   # найдёт собранный exe

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: client-exe
          path: .

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./*.exe   # загружаем exe в релиз
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
